package org.pragmatica.jbct.slice.generator;

import org.pragmatica.jbct.slice.model.MethodModel;
import org.pragmatica.jbct.slice.model.SliceModel;

import javax.annotation.processing.Filer;
import javax.lang.model.element.Modifier;
import javax.lang.model.util.Elements;
import javax.lang.model.util.Types;
import java.io.IOException;

import com.squareup.javapoet.JavaFile;
import com.squareup.javapoet.MethodSpec;
import com.squareup.javapoet.TypeName;
import com.squareup.javapoet.TypeSpec;

public class ApiInterfaceGenerator {
    private final Filer filer;
    private final Elements elements;
    private final Types types;

    public ApiInterfaceGenerator(Filer filer, Elements elements, Types types) {
        this.filer = filer;
        this.elements = elements;
        this.types = types;
    }

    public void generate(SliceModel model) throws IOException {
        var interfaceBuilder = TypeSpec.interfaceBuilder(model.simpleName())
                                       .addModifiers(Modifier.PUBLIC)
                                       .addJavadoc("API interface for $L slice.\n",
                                                   model.simpleName())
                                       .addJavadoc("Generated by slice-processor - do not edit manually.\n\n")
                                       .addJavadoc("@see $L\n",
                                                   model.qualifiedName());
        for (var method : model.methods()) {
            var methodSpec = generateMethod(method);
            interfaceBuilder.addMethod(methodSpec);
        }
        var javaFile = JavaFile.builder(model.apiPackage(),
                                        interfaceBuilder.build())
                               .indent("    ")
                               .build();
        javaFile.writeTo(filer);
    }

    private MethodSpec generateMethod(MethodModel method) {
        var builder = MethodSpec.methodBuilder(method.name())
                                .addModifiers(Modifier.PUBLIC, Modifier.ABSTRACT)
                                .returns(TypeName.get(method.returnType()))
                                .addParameter(TypeName.get(method.parameterType()),
                                              method.parameterName());
        if (method.deprecated()) {
            builder.addAnnotation(Deprecated.class);
        }
        return builder.build();
    }
}
